### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by basilgood** [abdellatif-dev/nvim-vigit#7]
**Describe the bug**
Nothing works.

**To Reproduce**
NVIM v0.5.0
LuaJIT 2.1.0-beta3

```use {'abdellatif-dev/nvim-vigit', branch = 'dev'}```

**Expected behavior**
```VGstatus``` gives current status of the repo ,like ```git status```

**Actual behavior**
Each command gives the same result:
```E5108: Error executing lua ...im/site/pack/packer/start/nvim-vigit/lua/vigit/vigit.lua:4: attempt to concatenate field 'vigit_bin' (a nil value)```

**Desktop (please complete the following information):**
 - OS: linux, NixOS

**Comment by abdellatif-dev** [comment]
hi,
i apologize for lack docs,i forgot to add one tiny thing which is
the fix is by adding this line to  ~/.config/nvim/lua/init.lua if you have it
```lua
require'vigit'.setup()
```
or you can put this in your init.vim
```vim
lua << EOF
require'vigit'.setup()
EOF
```
i'll makesure to add it in README.md right now

**Comment by basilgood** [comment]
Thanks, yes it works now.
